# User Registration
POST http://localhost:6969/register
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###

# User Login
POST http://localhost:6969/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###

# Create Subreddit (Authenticated)
POST http://localhost:6969/create-subreddit
Content-Type: application/json
Authorization: Bearer <YourAccessToken>

{
  "name": "programming",
  "description": "Discussion about programming"
}

###

# Create Post (Authenticated)
POST http://localhost:6969/create-post
Content-Type: application/json
Authorization: Bearer <YourAccessToken>

{
  "title": "Introduction to Node.js",
  "content": "Node.js is a JavaScript runtime built on Chrome's V8 JavaScript engine."
}

###

# Delete Post
DELETE http://localhost:6969/delete-post/:postId
Authorization: Bearer <your_token>

# Replace ":postId" with the actual ID of the post you want to delete

###

# Get All Posts
GET http://localhost:6969/get-all-posts

###

# Get Post by ID
GET http://localhost:6969/get-post/:postId

###

# Create Comment (Authenticated)
POST http://localhost:6969/create-comment/:postId
Content-Type: application/json
Authorization: Bearer <YourAccessToken>

{
  "content": "Great post! I learned a lot."
}

###

# Create Subreddit (Authenticated)
POST http://localhost:6969/create-subreddit
Content-Type: application/json
Authorization: Bearer <YourAccessToken>

{
  "name": "movies",
  "description": "Discussion about movies"
}

###

# Delete Subreddit (Authenticated)
DELETE http://localhost:6969/delete-subreddit/:subredditId
Authorization: Bearer <YourAccessToken>
